import streamlit as st

db_username="Sam"
db_password="123sam"

db_username="Nsofini"
db_password="123layter"

# st.write("DB username:", st.secrets["db_username"])
# st.write("DB password:", st.secrets["db_password"])
